spring:
    freemarker:
        settings:
            locale: pt_BR
    jackson:
        deserialization:
            fail-on-ignored-properties: true
            fail-on-unknown-properties: true       
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                '[format_sql]': true
        show-sql: true
    mail:
        host: smtp.sendgrid.net
        username: apikey
        port: '587'
        password: ${EMAIL_PASSWORD}
    web:
        resources:
            add-mappings: false
    datasource:
        password: ${DATA_SOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        url: jdbc:mysql://localhost/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
    output:
        ansi:
            enabled: NEVER
    flyway:
        locations: classpath:db/migration,classpath:db/testdata
    mvc:
        throw-exception-if-no-handler-found: true
        pathmatch:
                 matching-strategy: ANT_PATH_MATCHER
algafood:
    email:
        remetente: AlgaFoods - NÃO Responder <opvistar@gmail.com>
        tipo: sandbox
        sand-box:
            destinatarios:
                - opvistar@gmail.com
    storage:
        local:
            diretorio-fotos: /JAVA/ALGAWORKS_ESR/Projeto/algafood-api-catalogo
        s3:
            bucket: algafoods-glr
            regiao: us-east-1
            diretorio-fotos: catalogo
            id-chave-acesso: ${AWS_S3_KEY}
            chave-acesso-secreta: ${AWS_S3_SECRET_KEY}
        tipo: local
logging:
    level:
        org:
            springframework:
                web: DEBUG
        com:
            fasterxml:
                jackson:
                databind: DEBUG
          
server:
    error:
        include-message: always
        include-stacktrace: always
